### ISSUE TITLE
Add vignette on working with Seurat

### ISSUE THREAD

**Issue by drisso** [drisso/zinbwave#17]
See below for an example.

```{r}
seu <- CreateSeuratObject(raw.data = dat)
## here usual filtering, normalization, etc.
seu <- FindVariableGenes(object = seu, mean.function = ExpMean, dispersion.function = LogVMR,
                         x.low.cutoff = 0.0125, x.high.cutoff = 3, y.cutoff = 0.5)


## zinbwave
se <- SummarizedExperiment(dat) # put in the colData() part of the object at least batch
zinb <- zinbwave(se[seu@var.genes,],
                X = "~ Batch", # this has to match the column name in colData()
                K=10, epsilon=1000)
W <- reducedDim(zinb)

## set zinbwave as a dim reduction in Seurat
seu <- SetDimReduction(object = seu, reduction.type = "zinbwave", slot = "cell.embeddings",
                       new.data = W)
seu <- SetDimReduction(object = seu, reduction.type = "zinbwave", slot = "key",
                       new.data = "zinbwave")

## Find clusters
seu <- FindClusters(object = seu, reduction.type = "zinbwave", dims.use = 1:10, #this should match K
                    resolution = 0.6, print.output = 0, save.SNN = TRUE)

```

**Comment by julalipa** [comment]
Hi, I have been trying to get this vignette to work in Seurat. I manage to run it and get a tSNE plot, however the FindClusters function does not work for me with the zinbwave reduction method. First, I create a Seurat object and do the standard processing as normal and then as per your instructions:
 
> zinb <- zinbwave(se[EL_zinbwave@var.genes,], K=16)
> W <- reducedDim(zinb)
> EL_zinbwave <- SetDimReduction(EL_zinbwave, reduction.type = "zinbwave", slot = "cell.embeddings", new.data = W)
> EL_zinbwave <- SetDimReduction(EL_zinbwave, reduction.type = "zinbwave", slot = "key", new.data="zinbwave")
> EL_zinbwave <- FindClusters(object = EL_zinbwave, reduction.type = "zinbwave", dims.use = 1:16, resolution = 0.6, print.output = 0, save.SNN = TRUE)

**Error: all(dims >= dims.min) is not TRUE**

Do you have any suggestions as to why this error might occur?

**Comment by drisso** [comment]
Which version of Seurat and zinbwave are you using?

The code in my previous post worked for me with Seurat 2.2.1 (and zinbwave v. 1.1.5).

**Comment by julalipa** [comment]
Thanks for your reply! Perhaps that is the problem - I have zinbwave v. 1.0.0 . However, I just checked and that is the same version that you can download from Bioconductor. Where can I get the newer version from? Thanks for all your help :)

**Comment by drisso** [comment]
You can either install it directly from here with

```{r}
devtools::install_github("drisso/zinbwave")
```

or install the devel version of R and Bioconductor.

**Comment by julalipa** [comment]
Thanks for your help. In any case, I've updated Zinbwave and re-run the code but still the same error.

**Comment by drisso** [comment]
That's weird... can you try changing `dim.use` to a smaller value and see if you get the same error.

What does the following give you?
```
dim(W)
```

**Comment by PaigeVega** [comment]
I am working with Seurat 2.3.2 and Zinbwave 1.3.3.9001 (part of the develop version to fix a problem detailed in another thread). I'm using the code below and having issues as well.  First thing to note is that I couldn't get the CreateSeuratObject function to work without changing my zinbwave object (se_zinb_X) into a data frame rather than a matrix.  The more problematic errors that I get are below.

seu <- CreateSeuratObject(raw.data = as.data.frame(counts(se_zinb_X)))

seu <- SetDimReduction(object = seu, reduction.type = "zinbwave", slot = "cell.embeddings",
new.data = W)

seu <- SetDimReduction(object = seu, reduction.type = "zinbwave", slot = "key", new.data = "zinbwave") # remove this line

seu <- FindClusters(object = seu, reduction.type = "zinbwave", dims.use = 20, resolution = 0.6, 
print.output = 0, save.SNN = TRUE)

If I run all these lines, I get the following error:

Error in GetCellEmbeddings(object = object, reduction.type = reduction.type, :
Cell embeddings slot for zinbwave is empty.


But if I run the code without the 3rd line (where I indicated " # remove this line"), here is what I get:

Error in nn2(data = data.use, k=k.param, searchtype = "standard", eps = nn.eps) :
no points in data!
In addition:  Warning message:
In BuildSNN (object = object, genes.use = genes.use, reduction.type = reduction.type, :
k.param set larget than the number of cells. Setting k.param to number of cells -1.

It seems like the second SetDimReduction function is just overwriting what the first one accomplished since it indicates cell embeddings are missing, so could you clarify what the line is supposed to do?  I also don't know how to interpret the second error message, or why there are missing data points.  I know this might be more on the Seurat side of things, but I thought maybe it has to do with the structure of the zinbwave inputs.  But, it could also be an issue with version compatibility.

I would appreciate any help!  Thanks!

**Comment by drisso** [comment]
The second `SetDimReduction` does not overwrite the first, it's setting the key value for that reduction type. Again, what is the result of the following?

```
dim(W)
```

are you sure you're not just setting an empty slot? 

I've closed this issue because this is not an error of zinbwave but of Seurat. I'm happy to help, but you may have more luck talking to the Seurat maintainer.
