### ISSUE TITLE
Possible application of ZINB-WaVE model

### ISSUE THREAD

**Issue by tibo1** [drisso/zinbwave#20]
Dear Dr. Risso
I am working with dietary data where, for many food variables, a relatively large proportion of the participants have zero intake and these zeros represent actual outcome values, not missing values. Hence, I have nonnegative zero-inflated data that does not follow a Gaussian distribution even when disregarding the clumping at zero. 
Traditional PCA and EFA has been extensively used on this type of dietary data to derive dietary patterns (i.e. the latent variables), but I question if these methods are at all appropriate with this type of zero-inflated data. We have run PCA and ZINB-WaVE on a sub-sample of the data set and then simulated datasets based on the results of both models, and ZINB-WaVE is far superior in predicting a distribution similar to that of the original distribution. 
However, there is one aspect I am particularly curious about: In our dataset, the food variables are equivalent to the genes J and participants are equivalent to the cells n. We have over 80000 participants and about 80 food variables. We have set the epsilon argument to 1000 to attempt getting a better low level representation, but I am still wondering whether this model is appropriate to use with J being so low (when PCA and EFA have been used on this type of dietary data previously, some studies with fewer J’s that us still extract 2-3 components/factors). We have also set the common dispersion as false, as the basis of variance is different for each food variable. My questions to you are:
1.	Do you think that that ZINB-WaVE can be applied to our type of data?
2.	If yes to 1., do you have any specific recommendations about setting penalty terms?

Many thanks in advance, from Tiril

**Comment by drisso** [comment]
Hi Tiril,

thanks for trying our model and for the nice feedback!

I don't think that it's necessarily a problem to apply this model to datasets with small J, especially if you do not have any `V` covariates.

As I mentioned in other issues (e.g. #22) it is indeed tricky to find the "right" values for the penalty parameters. In general, you want values large enough to stabilize your estimates, but not so large that it creates issues with the initialization steps. In your case, because J is relatively low, the default value of epsilon (`epsilon=J`) might be too low, and I would try to increase that to 100 or 1000 and see how things change. However, since it seems from your note that you are satisfied with the current results, it may be that the current value of epsilon is good enough.

So, I'm afraid I don't have any specific recommendations on how to set the penalty terms, other than trying a few different values and see how robust are the results to these changes.
