### ISSUE TITLE
zinbFit parallel windows 7

### ISSUE THREAD

**Issue by XiangZhangSC** [drisso/zinbwave#24]
I have a integer matrix Y, and design matrix X. I ran 
library(BiocParallel)
zFit <- zinbwave::zinbFit(Y, X, BPPARAM=SnowParam(7))

But I find still my cpu usage is below 20%, so only one core was working. I am working on a desktop with 8 cores. Did I miss something here?

**Comment by drisso** [comment]
Your code seems fine to me.

On my Mac, your code uses 7 cores. I wonder if it's a Windows issue. Can you please try the following and see if it works?

```{r}
library(BiocParallel)
register(SnowParam(7))
zFit <- zinbwave::zinbFit(Y, X)
```

**Comment by XiangZhangSC** [comment]
Hi drisso,
Still the same. I could use BPPARAM option when I was working with DESeq2 before on the same windows machine. I wonder if you have any further suggestions?

**Comment by XiangZhangSC** [comment]
For some reason SnowParam() doesn't trigger parallel in windows 7
When I do 

library(doParallel)
registerDoParallel(cl = 6)

zFit <- zinbFit(Y, X, BPPARAM = BiocParallel::DoparParam())

Finally 6 cores start to work. Maybe this can be mentioned in the vignette. 
I will close this issue. Cheers!

**Comment by drisso** [comment]
Thanks for the feedback. This looks like a bizarre behavior of Snow and BiocParallel under windows. Since it works for me on my Mac. The bizarre part is that Snow works for you on a different package that also uses BiocParallel.

Please, consider posting this issue at support.bioconductor.org with the BiocParallel tag so that the core team of Bioconductor can help us figure out the issue.

Thanks!
