### ISSUE TITLE
Normalized value negative correlation with bulk

### ISSUE THREAD

**Issue by zji90** [drisso/zinbwave#46]
Hi,
I have tried zinbwave on one 10x HEK293t cell line dataset. zinbwave is run without specifying cell or gene level covariates. Then I calculated the correlation between the zinbwave normalized value of each individual cell with the corresponding HEK293t bulk RNA-seq sample and find that the correlation is mostly negative.
I wonder whether the normalized value is comparable to bulk RNA-seq in this case? Thanks!

**Comment by drisso** [comment]
Hi,

normalized values are meant to be only an exploratory summary for visualization, I would not recommend using it for anything other than that.

However, it does seem strange that there is a negative correlation with bulk RNA-seq samples. It's not easy to have an intuition on what to expect without knowing more about what you are doing. What do you mean by corresponding bulk samples? Do you have several cell lines and are you comparing the average single-cell profile vs the bulk? Or ... ?

**Comment by zji90** [comment]
Thanks for the reply. I run zinbwave on a 10x dataset with cells coming from 2 cell lines (HEK293t and Jurkat). For zinbwave I used all default settings, without specifying the gene or cell covariates. The normalized value from zinbwave is a gene * cell matrix. Then I calculated correlation between the normalized value for one HEK293t single cell and the bulk RNA-seq for HEK293t across all genes that are shared by both scRNA-seq and bulk RNA-seq. The resulting correlation is negative. I have tried other imputation methods (like saver and magic) and the correlation is usually around 0.6-0.8.

**Comment by drisso** [comment]
As I said in the previous comment, the normalized values are meant just for visualization and, most importantly, zinbwave is **not** an imputation method.

So I guess it's more or less expected that it does not lead to a correlation as high as the imputation methods that you mention. In fact one might even expect that some individual cells are quite distant from the bulk profile (which is an average of all cells in the sample) especially for heterogeneous tissues (otherwise why bother with single-cell RNA-seq?). I would expect that _the mean of all single cell profiles_ is correlated with the bulk profile.

In any case, if what you are looking for is an imputation method, zinbwave is not going to work.

**Comment by zji90** [comment]
Thanks a lot for your clarification!
