### ISSUE TITLE
Recovery of imputed values

### ISSUE THREAD

**Issue by kmuench** [drisso/zinbwave#53]
Hello,

I'm interested in using ZINB-WaVE for data imputation. However, I'm confused about how to retrieve the imputed data.

I see there is an ImputeZeros() function, although it is not deployed in the vignette. Is this function the correct method for retrieving imputed data? If so - I can create the count data input from the SingleCellExperiment() object, but what zinbmodel do I feed to it? Is there a way to use the model fitted by zinbwave?

Alternatively, is the data produced by zinbwave(..., normalizedValues=TRUE, ...) functionally the imputed data?

Thank you for your guidance.

**Comment by drisso** [comment]
Hi @kmuench 

First, I should note that ZINB-WaVE was not designed with imputation in mind. We did experiment a bit on imputation in the early days, but we were convinced pretty soon that other approaches may be better. 

So the fact that the imputation function is not widely used in the package or publicized in the vignette is by design. I would therefore advice against using zinbwave for data imputation.

If you really want to use the imputeZeros() function, the model in input is the output of the zinbFit() function, which works similarly to zinbwave(), but with more control over the parameters.

I hope this helps.
