### ISSUE TITLE
padjFilter column in edgeR results

### ISSUE THREAD

**Issue by vincr04** [drisso/zinbwave#55]
Hi all, 
I am calculating obervational weights in zinbwave and then running differential expression with edgeR. I understand the `glmWeightedF` function in edgeR allows adjustment of degrees of freedom by the extent of zero inflation, but I have a hard time understanding what the padjFilter values in the results table mean, how they are calculated, and why they seem to be identical to FDR values? 
Any help to understand this would be greatly appreciated!

**Comment by drisso** [comment]
Hi @vincr04 

the `padjFilter` column is related to the `independentFiltering` option. If TRUE (default) an independent filtering step is applied prior to the multiple testing procedure, as described in great details in the `DESeq2` vignette: http://bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#indfilttheory

They are identical to the FDR values if the filtering step does not remove any gene, since the function uses the Benjamini-Hochberg correction by default. If the procedure filters some genes the adjusted p-values will differ from the FDR column, typically resulting in greater power to detect DE genes.

The theory behind independent filtering is described in:
Bourgon, Richard, Robert Gentleman, and Wolfgang Huber. 2010. “Independent Filtering Increases Detection Power for High-Throughput Experiments.” PNAS 107 (21): 9546–51. http://www.pnas.org/content/107/21/9546.long.

I'm adding a similar description to the man page of the function for future reference.

Best,
Davide
