### ISSUE TITLE
Normalized dataset

### ISSUE THREAD

**Issue by zji90** [drisso/zinbwave#7]
Hi,
We find zinbwave very useful for analyzing the scRNA-seq data we have. One question is that can we obtain the normalized data for the whole dataset, in addition to the dataset after filtering? More specifically, say we have 20000 genes in the original dataset. We first filter out the lowly expressed genes and genes with low variations, and 1000 genes are left. We use these 1000 genes to run zinbwave and get the normalized data using the zinbwave function. However, the normalized data is only for the 1000 genes. Can we somehow get the normalized data for the original 20000 genes, so that we can perform the follow up analysis such as differential test for all the genes in the dataset? Otherwise we may need to run zinbwave on the 20000 genes, which is too slow and may affect the performance of the algorithm. Thanks!

**Comment by drisso** [comment]
I'm glad that you find zinbwave useful for your analyses!

Please, note that the normalized counts functionality is still an experimental feature. We haven't tested it thoroughly. 

That said, you don't need W to compute the normalized values as we define it in the model. Hence, you can re-fit the model without W to get the normalized counts (this would be faster). My suggested pipeline would be:

1. Fit a first zinbwave model with the top 1000 genes to estimate W (what you already did).
2. Re-fit zinbwave without W (i.e., with K=0) for all the genes to get the normalized counts.

Because the method is quadratic in K, reducing K to 0 should make it faster and feasible to run even with 20,000 genes.

**Comment by zji90** [comment]
Thanks! I will try it out. I am running zinbwave to estimate W on a dataset with around 3000 genes and 750 cells. The program is run on a cluster with 30 cores, but it seems that zinbwave hasn't finished yet after 5 hours. Do you have any suggestion how to speed up the program? For example how to specify the parameters?

**Comment by drisso** [comment]
What is the value of K? 5 hours seems way too much for just 750 cells in my experience.

One counter-intuitive solution might be to reduce the number of cores. I haven't thoroughly profiled the code yet, but I've generally seen that the memory usage increases a lot with the number of cores (although it might just be virtual memory... I'm not good at this! :)). Anyway, I'd try reducing to 8 cores and see if it speeds up.

**Comment by zji90** [comment]
K=2 in my case. I will try reducing to 8 cores and see what happens.
